### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by sullyjake20** [shieldnet/Youtube-livestream-api-bot#14]
My acc expired on 17.07.2020. I paid at 18,07.2020 ( 23:16 mins) but I still do not have access to the stream btt. Can you confirm the payment?

Youtube Channel: https://www.youtube.com/channel/UCtoWfrmZCfpm05DbD_PwaMw
Reference Number:  238177364
Youtube number: UCtoWfrmZCfpm05DbD_PwaMw

**Comment by shieldnet** [comment]
I'm sorry to hear that.

But we can't solve your problem because we are not the official API supporter. 

I recommend you to contact official youtube customer service center or QnA. Also, you must not post your Channel ID, or sth. like that.

Have a nice day. Close #14
